//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindBackOffice.CustomerServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dotnetmentors.com/services/customer", ConfigurationName="CustomerServiceRef.ICustomerService")]
    public interface ICustomerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerName", ReplyAction="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerNameRespon" +
            "se")]
        string GetCustomerName(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerCity", ReplyAction="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerCityRespon" +
            "se")]
        string GetCustomerCity(int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerCount", ReplyAction="http://dotnetmentors.com/services/customer/ICustomerService/GetCustomerCountRespo" +
            "nse")]
        int GetCustomerCount();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServiceChannel : NorthwindBackOffice.CustomerServiceRef.ICustomerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceClient : System.ServiceModel.ClientBase<NorthwindBackOffice.CustomerServiceRef.ICustomerService>, NorthwindBackOffice.CustomerServiceRef.ICustomerService {
        
        public CustomerServiceClient() {
        }
        
        public CustomerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCustomerName(int CustomerID) {
            return base.Channel.GetCustomerName(CustomerID);
        }
        
        public string GetCustomerCity(int CustomerID) {
            return base.Channel.GetCustomerCity(CustomerID);
        }
        
        public int GetCustomerCount() {
            return base.Channel.GetCustomerCount();
        }
    }
}
