//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReferenceEmp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceEmp.IEmpInfoService")]
    public interface IEmpInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpInfoService/GetEmpSalary", ReplyAction="http://tempuri.org/IEmpInfoService/GetEmpSalaryResponse")]
        string GetEmpSalary(string empId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpInfoService/GetEmpSalary", ReplyAction="http://tempuri.org/IEmpInfoService/GetEmpSalaryResponse")]
        System.Threading.Tasks.Task<string> GetEmpSalaryAsync(string empId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpInfoServiceChannel : ConsoleApplication1.ServiceReferenceEmp.IEmpInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpInfoServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReferenceEmp.IEmpInfoService>, ConsoleApplication1.ServiceReferenceEmp.IEmpInfoService {
        
        public EmpInfoServiceClient() {
        }
        
        public EmpInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmpSalary(string empId) {
            return base.Channel.GetEmpSalary(empId);
        }
        
        public System.Threading.Tasks.Task<string> GetEmpSalaryAsync(string empId) {
            return base.Channel.GetEmpSalaryAsync(empId);
        }
    }
}
